### ISSUE TITLE
Change Ship - Choose ship can be clicked multiple times; decrementing XP each time.

### ISSUE THREAD

**Issue by bdwakefield** [grahamgilchrist/hotac-squad-builder#126]
Add a bunch of XP and level up the pilot to PS4. Select [Change Ship]. Choose a ship and and click [Choose Ship] multiple times. Observe current XP continue to decrease into the negative.
![image](https://user-images.githubusercontent.com/3208406/32525512-cd4695ac-c3f2-11e7-9e30-6ee3f0851a30.png)

**Comment by grahamgilchrist** [comment]
Hmm the button should grey out and be disabled when you don't have enough Xp or are lower than PS4

I can't reproduce this.

Could you provide a few more details. Browser/device/OS version, and maybe some screenshots of the steps?

**Comment by grahamgilchrist** [comment]
Hmm wait now I can reproduce this. wierd. will take a look

**Comment by grahamgilchrist** [comment]
Ok right, sorry. i was working in another branch where I had already fixed this issue. 

Fixed in #133

**Comment by bdwakefield** [comment]
Sweet!
