### ISSUE TITLE
Error running application

### ISSUE THREAD

**Issue by bdwakefield** [grahamgilchrist/hotac-squad-builder#127]
While attempting to run and build the deployable package using npx I get the following output:

`> npx run gulp
npx: installed 1 in 1.019s
Path must be a string. Received undefined
npx: installed 5 in 1.258s
C:\Users\<user>\AppData\Roaming\npm-cache\_npx\10580\node_modules\run\cli.js
Watching D:\source\hotac-squad-builder and all sub-directories not excluded by your .gitignore. Will not monitor dotfiles.
Found & ignored ./.git ; is listed in .gitignore
Found & ignored ./app ; is listed in .gitignore
Found & ignored ./docs ; is listed in .gitignore
Found & ignored ./js-src ; is listed in .gitignore
Found & ignored ./node ; is listed in .gitignore
Found & ignored ./node_modules ; is listed in .gitignore
Found & ignored ./sass ; is listed in .gitignore
Found & ignored ./src-templates ; is listed in .gitignore
Found & ignored ./bower.json ; is listed in .gitignore
Found & ignored ./circle.yml ; is listed in .gitignore
Found & ignored ./gulpfile.js ; is listed in .gitignore
Found & ignored ./LICENSE ; is listed in .gitignore
Found & ignored ./package-lock.json ; is listed in .gitignore
Found & ignored ./package.json ; is listed in .gitignore
Found & ignored ./readme.md ; is listed in .gitignore

Starting: gulp
module.js:538
    throw err;
    ^

Error: Cannot find module 'D:\source\hotac-squad-builder\gulp'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3`

I have completely removed and reinstalled node/npm and I get the same result. I have insured that gulp and bower are both installed globally. I have removed the node_modules folder and re-run npm install several times.

Advice?

**Comment by grahamgilchrist** [comment]
Some initial thoughts:
* `npx` needs npm => 5.2, which I think ships with one of the node 8.2?. Maybe make sure you have the absolute latest version (currently 9.1.0)
* It looks like you are using this one windows? I know you can install node on windows, but it's not something I have a lot of experience with. You might have better luck on a *nix platform like linux or macOS?

**Comment by bdwakefield** [comment]
I have access to both; I will give it a try on my mac tonight.

**Comment by bdwakefield** [comment]
Same/similar result on the mac.
node -v => 8.9.1
npm -v => 5.5.1

**Comment by bdwakefield** [comment]
This is bummin me out; I completed nuked node and npm and [reinstalled](https://github.com/npm/npm/issues/19032#issuecomment-341420966). Same error.

**Comment by bdwakefield** [comment]
Brand new Ubuntu VM (17.10). Installed node fresh. Same result.

**Comment by bdwakefield** [comment]
![image](https://user-images.githubusercontent.com/3208406/32587510-d0cecc96-c4d6-11e7-9a86-afe6fa7931c3.png)

**Comment by grahamgilchrist** [comment]
Ah, sorry I noticed an error in the readme. It's just `npx gulp dev`. There's no '`run` part of the command. Not sure where that came from...

**Comment by bdwakefield** [comment]
Yeah; I am not super familiar with node stuff at the moment else I probably would have caught that.

**Comment by bdwakefield** [comment]
Thanks!
