### ISSUE TITLE
Add a way to include Squad Leader on the character sheet

### ISSUE THREAD

**Issue by cahlash** [grahamgilchrist/hotac-squad-builder#170]
Perhaps add a checkbox option in the upgrades area?

**Comment by grahamgilchrist** [comment]
Coding wise, I don't think this is that complicated. 
It's mostly a UX problem of where to put the checkbox that doesn't clutter the interface. i will have a think

**Comment by grahamgilchrist** [comment]
The obvious answer which only just occured to me was to treat this as any other "free" starting upgrade, which lets it be equipped at any point for no cost.

This is done in #181
