### ISSUE TITLE
"Crimson Specialist" and "Cobalt Leader" pilot abilities missing from EPT selection.

### ISSUE THREAD

**Issue by cahlash** [grahamgilchrist/hotac-squad-builder#171]
Crimson Leader seems to be the only pilot ability that made it in from the Resistance Bomber xpack.

http://xwing-miniatures.wikia.com/wiki/%22Crimson_Specialist%22

http://xwing-miniatures.wikia.com/wiki/%22Cobalt_Leader%22

**Comment by grahamgilchrist** [comment]
This presumably just needs a rebuild with the latest version of https://github.com/guidokessels/xwing-data

**Comment by grahamgilchrist** [comment]
Updated to latest xwing data which has added the latest upgrades
