### ISSUE TITLE
Cannot Purchase Ion Cannon Turret

### ISSUE THREAD

**Issue by tdk1007** [grahamgilchrist/hotac-squad-builder#77]
Unable to purchase the ion cannon turret on the Y-Wing

Using the version hosted on netlify
http://hotac-ship-builder.netlify.com/

**Comment by grahamgilchrist** [comment]
I can't seem to reproduce this. It works on all my test devices.
What browser are you using?
Are you creating a ship from scratch or editing an existing one?
Do you have a URL link for the broken ship you are having issues with?

**Comment by tdk1007** [comment]
It's now working for me on the latest build.
