### ISSUE TITLE
Cannot create new ship.

### ISSUE THREAD

**Issue by Galaxy613** [grahamgilchrist/hotac-squad-builder#96]
From Reddit: https://www.reddit.com/r/XWingTMG/comments/7a5fmj/hotac_ship_builder_site/

As soon as you press "Start" after putting in a name and callsign, it tries to continue but returns you to the start screen. In the (Chrome) console it spits out:
```
Unhandled promise rejection Error: Loading chunk 0 failed.
Stack trace:
e@http://hotac-ship-builder.netlify.com/js/vendor/json-url/json-url.js:1:738
 json-url.js:1:45068

Unhandled promise rejection Error: Loading chunk 0 failed.
Stack trace:
e@http://hotac-ship-builder.netlify.com/js/vendor/json-url/json-url.js:1:738
```

~Apparently effects all browsers?~
Personally tested only on Windows 7/8, on IE11, Chrome and Firefox

**Comment by Galaxy613** [comment]
Alrighty, I got the repo building. I'm going to try to explore this issue (despite my minimal JS knowledge xD)

**Comment by grahamgilchrist** [comment]
Thanks for the bug report. I'll take a look.

This is still totally alpha software. Nominally the "Public alpha" milestone was the point I was working to have a stable version to be announced and released to the public. I'm amazed anyone knew this project existed yet! (but happy you find it useful)

I've just merged the last issue I had on the list for the alpha (fixing the print layout a bit better) so I'll take a look at this :)

**Comment by grahamgilchrist** [comment]
I think this is related to the JSON URL library, which does some asynchronously loading which i think may be causing the issue. Strangely I don't get this on my local development machine, so perhaps it is something to do with the javascript aggregation on Netlify. I'll take a look.

**Comment by grahamgilchrist** [comment]
Interestingly, this issue doesn't manifest on android chrome, only desktop chrome

**Comment by Galaxy613** [comment]
But you *were* able to recreate it? That's good

**Comment by grahamgilchrist** [comment]
Yes, I have been able to recreate locally. It also only happens on the first page load. If you link via URL into an existing ship build, the page loads fine, and then if you "Start a new ship" from there, it also works fine. It is only completely new page loads from the root URL which fail.

I'll continue to investigate

**Comment by grahamgilchrist** [comment]
Ok, it looks like when clicking the button, it was actually submitting the html form and refreshing the page, which is not supposed to happen unless the button had `type="submit"`. Perhaps because it was the only button in the form some browsers pick it as the default submit?

Regardless, I've prevented the submit action via javascript, so it is now working again :)

**Comment by Galaxy613** [comment]
BTW - now that I can actually use this, I LOVE this! I definitely going to keep poking around and try to do some simple changes later. :)
